apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: skilltest
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: myapp
        image: thirumalaipy/ms-product:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
